DOAN/Models/tblDanhMucSP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblDanhMucSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDanhMucSP()
        {
            this.tblSanPhams = new HashSet<tblSanPham>();
        }
    
        [Key]
        public int MaDanhMuc { get; set; }
        [Required(ErrorMessage ="Bạn chưa nhập tên danh mục!")]
        public string TenDanhMuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSanPham> tblSanPhams { get; set; }
    }
}

DOAN/Areas/Admin/Controllers/tblDanhMucSPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DOAN.Models;

namespace DOAN.Areas.Admin.Controllers
{
    public class tblDanhMucSPsController : Controller
    {
        private QuanLyBanHangEntities1 db = new QuanLyBanHangEntities1();

        // GET: Admin/tblDanhMucSPs
        public ActionResult Index(string SearchString = "")
        {
            if (SearchString != "")
            {
                var DanhMucSP = db.tblDanhMucSPs.Where(x => x.TenDanhMuc.ToUpper().Contains(SearchString.ToUpper()));
                return View(DanhMucSP.ToList());
            }
            var lstDanhMuc = db.tblDanhMucSPs.ToList();
            return View(lstDanhMuc);
        }

        // GET: Admin/tblDanhMucSPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDanhMucSP tblDanhMucSP = db.tblDanhMucSPs.Find(id);
            if (tblDanhMucSP == null)
            {
                return HttpNotFound();
            }
            return View(tblDanhMucSP);
        }

        // GET: Admin/tblDanhMucSPs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/tblDanhMucSPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDanhMuc,TenDanhMuc")] tblDanhMucSP tblDanhMucSP)
        {
            if (ModelState.IsValid)
            {
                db.tblDanhMucSPs.Add(tblDanhMucSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblDanhMucSP);
        }

        // GET: Admin/tblDanhMucSPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDanhMucSP tblDanhMucSP = db.tblDanhMucSPs.Find(id);
            if (tblDanhMucSP == null)
            {
                return HttpNotFound();
            }
            return View(tblDanhMucSP);
        }

        // POST: Admin/tblDanhMucSPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDanhMuc,TenDanhMuc")] tblDanhMucSP tblDanhMucSP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblDanhMucSP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblDanhMucSP);
        }

        // GET: Admin/tblDanhMucSPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDanhMucSP tblDanhMucSP = db.tblDanhMucSPs.Find(id);
            if (tblDanhMucSP == null)
            {
                return HttpNotFound();
            }
            return View(tblDanhMucSP);
        }

        // POST: Admin/tblDanhMucSPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblDanhMucSP tblDanhMucSP = db.tblDanhMucSPs.Find(id);
            db.tblDanhMucSPs.Remove(tblDanhMucSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult MenuDM()
        {
            return PartialView("MenuDM", db.tblDanhMucSPs.ToList());
        }
    }
}

DOAN/Areas/Admin/Views/tblDanhMucSPs/Create.cshtml
@model DOAN.Models.tblDanhMucSP

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .text-color {
        color: #3c3d46;
    }
</style>

<h2 class="text-color">Thêm mới danh mục sản phẩm</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text-color">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">Tên danh mục</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDanhMuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Danh sách", "Index")
</div>

DOAN/Areas/Admin/Views/tblDanhMucSPs/Delete.cshtml
@model DOAN.Models.tblDanhMucSP

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .text-color {
        color: #3c3d46;
    }
</style>
<h3 class="text-color">Bạn có chắc chắn xóa danh mục này không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal text-color">
        <dt>
            Tên danh mục
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDanhMuc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-primary" /> |
            @Html.ActionLink("Danh sách", "Index")
        </div>
    }
</div>

DOAN/Areas/Admin/Views/tblDanhMucSPs/Details.cshtml
@model DOAN.Models.tblDanhMucSP

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .text-color {
        color: #3c3d46;
    }
</style>

<h2 class="text-color">Thông tin chi tiết danh mục</h2>

<div>
    <hr />
    <dl class="dl-horizontal text-color">
        <dt>
            Mã danh mục:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDanhMuc)
        </dd>

        <dt>
            Tên danh mục:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDanhMuc)
        </dd>

    </dl>
</div>
@Html.Action("SanPhamTheoDanhMuc1", "tblSanPhams", new { id = Model.MaDanhMuc, matt = Model.MaDanhMuc })

<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaDanhMuc }) |
    @Html.ActionLink("Danh sách", "Index")
</p>

DOAN/Areas/Admin/Views/tblDanhMucSPs/Edit.cshtml
@model DOAN.Models.tblDanhMucSP

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .text-color {
        color: #3c3d46;
    }
</style>

<h2 class="text-color">Sửa danh mục</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal text-color">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaDanhMuc)

    <div class="form-group">
        <div class="control-label col-md-2">Mã danh mục</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaDanhMuc, new { htmlAttributes = new { @class = "form-control", @readonly="readonly" } })
            @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Tên danh mục</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenDanhMuc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenDanhMuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Danh sách", "Index")
</div>

DOAN/Areas/Admin/Views/tblDanhMucSPs/Index.cshtml
@model IEnumerable<DOAN.Models.tblDanhMucSP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DANH SÁCH DANH MỤC</h6>
        </div>
        @if (Session["role"] != null)
        {
            if (Session["role"].ToString() == Constant.ADMIN)
            {
                <a class="btn btn-primary ml-4 mt-2 pl-2" href="@Url.Action("Create")" style="width: 6rem;">Thêm mới</a>
            }
        }
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered dataTable text-dark" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Mã danh mục</th>
                            <th>Tên danh mục</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MaDanhMuc)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenDanhMuc)
                                </td>
                                <td>
                                    @if (Session["role"] != null)
                                    {
                                        if (Session["role"].ToString() == Constant.ADMIN)
                                        {
                                            <a href="@Url.Action("Edit","tblDanhMucSPs", new {id = item.MaDanhMuc})" class="p-1 data-toggle= text-primary">Sửa</a><span>|</span>
                                            <a href="@Url.Action("Details","tblDanhMucSPs", new {id = item.MaDanhMuc})" class="p-1 data-toggle= text-primary">Chi tiết</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("Details","tblDanhMucSPs", new {id = item.MaDanhMuc})" class="p-1 data-toggle= text-primary">Chi tiết</a>

                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@section scripts{
    <script src="~/Areas/Admin/assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.dataTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.11.5/i18n/vi.json'
                },
            });
        });
    </script>
}

DOAN/Areas/Admin/Views/tblDanhMucSPs/MenuDM.cshtml
@model List<DOAN.Models.tblDanhMucSP>
@foreach (var item in Model)
{
    <tr>
        <td>
            <a href="@Url.Action("SanPhamTheoDanhMuc1", "tblSanPhams", new { id = item.MaDanhMuc})" class="nav-item nav-link pt-3 pb-3">
                @Html.DisplayFor(modelItem => item.TenDanhMuc)
            </a>
        </td>
    </tr>
}