DOAN/Models/tblNguoiDung.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblNguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNguoiDung()
        {
            this.tblBinhLuans = new HashSet<tblBinhLuan>();
            this.tblDonHangs = new HashSet<tblDonHang>();
            this.tblPhieuNhaps = new HashSet<tblPhieuNhap>();
        }
    
        [Key]
        public int MaNguoiDung { get; set; }
        [Required(ErrorMessage ="Bạn chưa nhập họ và tên!")]
        public string TenNguoiDung { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public int MaQuyen { get; set; }
        public int MaTrangThai { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBinhLuan> tblBinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonHang> tblDonHangs { get; set; }
        public virtual tblQuyen tblQuyen { get; set; }
        public virtual tblTrangThai tblTrangThai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuNhap> tblPhieuNhaps { get; set; }
    }
}

DOAN/Areas/Admin/Controllers/tblNguoiDungsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DOAN.Models;

namespace DOAN.Areas.Admin.Controllers
{
    public class tblNguoiDungsController : Controller
    {
        private QuanLyBanHangEntities1 db = new QuanLyBanHangEntities1();

        // GET: Admin/tblNguoiDungs
        public ActionResult Index(string SearchString = "")
        {
            if(SearchString != "")
            {
                var user = db.tblNguoiDungs.Where(x => x.TenNguoiDung.ToUpper().Contains(SearchString.ToUpper()));
                return View(user.ToList());
            }
            var lstNguoiDung = db.tblNguoiDungs.Where(x => x.MaQuyen == 5).ToList();
            return View(lstNguoiDung);
            //var tblNguoiDungs = db.tblNguoiDungs.Include(t => t.tblQuyen).Include(t => t.tblTrangThai);
            //return View(tblNguoiDungs.ToList());
        }

        // GET: Admin/tblNguoiDungs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNguoiDung tblNguoiDung = db.tblNguoiDungs.Find(id);
            if (tblNguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(tblNguoiDung);
        }

        // GET: Admin/tblNguoiDungs/Create
        public ActionResult Create()
        {
            ViewBag.MaQuyen = new SelectList(db.tblQuyens, "MaQuyen", "TenQuyen");
            ViewBag.MaTrangThai = new SelectList(db.tblTrangThais.Where(x => x.MaLTT == 1), "MaTrangThai", "TenTrangThai");
            return View();
        }

        // POST: Admin/tblNguoiDungs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNguoiDung,TenNguoiDung,NamSinh,GioiTinh,DiaChi,SDT,MaQuyen,MaTrangThai,TenDangNhap,MatKhau")] tblNguoiDung tblNguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.tblNguoiDungs.Add(tblNguoiDung);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaQuyen = new SelectList(db.tblQuyens, "MaQuyen", "TenQuyen", tblNguoiDung.MaQuyen);
            ViewBag.MaTrangThai = new SelectList(db.tblTrangThais.Where(x => x.MaLTT == 1), "MaTrangThai", "TenTrangThai", tblNguoiDung.MaTrangThai);
            return View(tblNguoiDung);
        }

        // GET: Admin/tblNguoiDungs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNguoiDung tblNguoiDung = db.tblNguoiDungs.Find(id);
            if (tblNguoiDung == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaQuyen = new SelectList(db.tblQuyens, "MaQuyen", "TenQuyen", tblNguoiDung.MaQuyen);
            ViewBag.MaTrangThai = new SelectList(db.tblTrangThais.Where(x => x.MaLTT == 1), "MaTrangThai", "TenTrangThai", tblNguoiDung.MaTrangThai);
            return View(tblNguoiDung);
        }

        // POST: Admin/tblNguoiDungs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNguoiDung,TenNguoiDung,NamSinh,GioiTinh,DiaChi,SDT,MaQuyen,MaTrangThai,TenDangNhap,MatKhau")] tblNguoiDung tblNguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblNguoiDung).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaQuyen = new SelectList(db.tblQuyens, "MaQuyen", "TenQuyen", tblNguoiDung.MaQuyen);
            ViewBag.MaTrangThai = new SelectList(db.tblTrangThais, "MaTrangThai", "TenTrangThai", tblNguoiDung.MaTrangThai);
            return View(tblNguoiDung);
        }

        // GET: Admin/tblNguoiDungs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNguoiDung tblNguoiDung = db.tblNguoiDungs.Find(id);
            if (tblNguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(tblNguoiDung);
        }

        // POST: Admin/tblNguoiDungs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblNguoiDung tblNguoiDung = db.tblNguoiDungs.Find(id);
            db.tblNguoiDungs.Remove(tblNguoiDung);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DSNhanVien()
        {
            var NhanVien = db.tblNguoiDungs.Where(x => x.MaQuyen == 4);
            return View(NhanVien.ToList());
        }
        public ActionResult DSKhachHang()
        {
            var NhanVien = db.tblNguoiDungs.Where(x => x.MaQuyen == 5);
            return View(NhanVien.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DOAN/Areas/Admin/Views/tblNguoiDungs/Create.cshtml
@model DOAN.Models.tblNguoiDung

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm tài khoản</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="control-label col-md-2">Tên người dùng</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenNguoiDung, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenNguoiDung, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Năm sinh</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.NamSinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NamSinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Giới tính</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Địa chỉ</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Số điện thoại</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Tên đăng nhập</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenDangNhap, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Mật khẩu</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Quyền truy cập</div>
        <div class="col-md-10">
            @Html.DropDownList("MaQuyen", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaQuyen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Trạng thái tài khoản</div>
        <div class="col-md-10">
            @Html.DropDownList("MaTrangThai", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaTrangThai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Danh sách", "Index")
</div>

DOAN/Areas/Admin/Views/tblNguoiDungs/DSKhachHang.cshtml
@model IEnumerable<DOAN.Models.tblNguoiDung>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DANH SÁCH KHÁCH HÀNG</h6>
        </div>
        @*<a class="btn btn-primary ml-4 mt-2 pl-2" href="@Url.Action("Create")" style="width: 6rem;">Thêm mới</a>
        <a class="pl-4 pt-4" href="~/Admin/tblNguoiDungs/DSNhanVien">Danh sách nhân viên</a>*@

        <div class="card-body text-dark">
            <div class="table-responsive">
                <table class="table table-bordered dataTable text-dark" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Tên khách hàng</th>
                            <th>Giới tính</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Quyền truy cập</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenNguoiDung)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GioiTinh)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DiaChi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SDT)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tblQuyen.TenQuyen)
                            </td>
                            <td>
                                @*<a href="@Url.Action("Edit","tblNguoiDungs", new {id = item.MaNguoiDung })" class="p-1 data-toggle= text-primary">Sửa</a><span>|</span>*@
                                <a href="@Url.Action("Details","tblNguoiDungs", new {id = item.MaNguoiDung })" class="p-1 data-toggle= text-primary">Chi tiết</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@section scripts{
    <script src="~/Areas/Admin/assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.dataTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.11.5/i18n/vi.json'
                },
            });
        });
    </script>
}

DOAN/Areas/Admin/Views/tblNguoiDungs/DSNhanVien.cshtml
@model IEnumerable<DOAN.Models.tblNguoiDung>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
<link href="~/Areas/Admin/assets/js/lib/css/bootstrap-datepicker3.min.css" rel="stylesheet" />
<style>
    .datepicker > .datepicker-days {
        display: block;
    }

    ol.linenums {
        margin: 0 0 0 -8px;
    }
</style>
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DANH SÁCH NHÂN VIÊN</h6>
        </div>
        <a class="btn btn-primary ml-4 mt-2 pl-2" href="@Url.Action("Create")" style="width: 6rem;">Thêm mới</a>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered dataTable text-dark" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Mã nhân viên</th>
                            <th>Tên nhân viên</th>
                            <th>Năm sinh</th>
                            <th>Giới tính</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Tên đăng nhập</th>
                            <th>Trạng thái tài khoản</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MaNguoiDung)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenNguoiDung)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NamSinh)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GioiTinh)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DiaChi)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SDT)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenDangNhap)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.tblTrangThai.TenTrangThai)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit","tblNguoiDungs", new {id = item.MaNguoiDung })" class="p-0 btn data-toggle= text-primary">Sửa</a><span>|</span>
                                    <a href="@Url.Action("Details","tblNguoiDungs", new {id = item.MaNguoiDung })" class="p-0 btn data-toggle= text-primary">Chi tiết</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{


    <script src="~/Areas/Admin/assets/js/lib/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Areas/Admin/assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.dataTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.11.5/i18n/vi.json'
                },
                "bFilter": false
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.startDate').datepicker({
                autoclose: true,
                format: 'dd/mm/yyyy',
            });
            $('.endDate').datepicker({
                autoclose: true,
                format: 'dd/mm/yyyy',
            });

        });
    </script>
}

DOAN/Areas/Admin/Views/tblNguoiDungs/Delete.cshtml
@model DOAN.Models.tblNguoiDung

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblNguoiDung</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNguoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNguoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NamSinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamSinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenDangNhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDangNhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblQuyen.TenQuyen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblQuyen.TenQuyen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblTrangThai.TenTrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTrangThai.TenTrangThai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DOAN/Areas/Admin/Views/tblNguoiDungs/Details.cshtml
@model DOAN.Models.tblNguoiDung

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thông tin chi tiết tài khoản</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Mã người dùng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNguoiDung)
        </dd>

        <dt>
            Tên người dùng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNguoiDung)
        </dd>

        <dt>
            Năm sinh:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamSinh)
        </dd>

        <dt>
            Giới tính:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Số điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            Tên đăng nhập:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDangNhap)
        </dd>

        @*<dt>
            Mật khẩu:
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>*@

        <dt>
            Quyền truy cập:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblQuyen.TenQuyen)
        </dd>

        <dt>
            Trạng thái truy cập:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTrangThai.TenTrangThai)
        </dd>

    </dl>
</div>
<p>
    @*@if (Session["role"].ToString() == Constant.ADMIN)
    {
        @Html.ActionLink("Sửa", "Edit", new { id = Model.MaNguoiDung })<span>|</span>
        @Html.ActionLink("Danh sách", "Index")
    }
    else if (Session["role"].ToString() == Constant.EMPLOYEER)
    {
        @Html.ActionLink("Danh sách", "DSKhachHang")
    }*@
</p>

DOAN/Areas/Admin/Views/tblNguoiDungs/Index.cshtml
@model IEnumerable<DOAN.Models.tblNguoiDung>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
@*<a class="btn btn-primary ml-4 pl-3" href="@Url.Action("Create")">Thêm</a>*@
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DANH SÁCH TÀI KHOẢN</h6>
        </div>
        <a class="btn btn-primary ml-4 mt-2 pl-2" href="@Url.Action("Create")" style="width: 6rem;">Thêm mới</a>
        <a class="pl-4 pt-4" href="~/Admin/tblNguoiDungs/DSNhanVien">Danh sách nhân viên</a>

        <div class="card-body text-dark">
            <div class="table-responsive">
                <table class="table table-bordered dataTable text-dark" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Tên người dùng</th>
                            <th>Tên đăng nhập</th>
                            <th>Quyền truy cập</th>
                            <th width="20%">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenNguoiDung)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenDangNhap)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.tblQuyen.TenQuyen)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit","tblNguoiDungs", new {id = item.MaNguoiDung })" class="p-1 data-toggle= text-primary">Sửa</a><span>|</span>
                                    <a href="@Url.Action("Details","tblNguoiDungs", new {id = item.MaNguoiDung })" class="p-1 data-toggle= text-primary">Chi tiết</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@section scripts{
    <script src="~/Areas/Admin/assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.dataTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.11.5/i18n/vi.json'
                },
            });
        });
    </script>
}