DOAN/Models/tblNhaCungCap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblNhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhaCungCap()
        {
            this.tblPhieuNhaps = new HashSet<tblPhieuNhap>();
            this.tblSanPhams = new HashSet<tblSanPham>();
        }
    
        [Key]
        public int MaNCC { get; set; }
        [Required(ErrorMessage ="Bạn chưa nhập tên nhà cung cấp!")]
        public string TenNCC { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ nhà cung cấp!")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập số điện thoại nhà cung cấp!")]
        [RegularExpression(@"[0-9]{10}", ErrorMessage ="Số điện thoại không đúng!")]
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuNhap> tblPhieuNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSanPham> tblSanPhams { get; set; }
    }
}

DOAN/Areas/Admin/Controllers/tblNhaCungCapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DOAN.Models;

namespace DOAN.Areas.Admin.Controllers
{
    public class tblNhaCungCapsController : Controller
    {
        private QuanLyBanHangEntities1 db = new QuanLyBanHangEntities1();

        // GET: Admin/tblNhaCungCaps
        public ActionResult Index(string SearchString = "")
        {
            if (SearchString != "")
            {
                var NhaCungCap = db.tblNhaCungCaps.Where(x => x.TenNCC.ToUpper().Contains(SearchString.ToUpper()));
                return View(NhaCungCap.ToList());
            }
            var lstNhaCC = db.tblNhaCungCaps.ToList();
            return View(lstNhaCC);
        }

        // GET: Admin/tblNhaCungCaps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNhaCungCap tblNhaCungCap = db.tblNhaCungCaps.Find(id);
            if (tblNhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(tblNhaCungCap);
        }

        // GET: Admin/tblNhaCungCaps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/tblNhaCungCaps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNCC,TenNCC,DiaChi,SDT")] tblNhaCungCap tblNhaCungCap)
        {
            if (ModelState.IsValid)
            {
                db.tblNhaCungCaps.Add(tblNhaCungCap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblNhaCungCap);
        }

        // GET: Admin/tblNhaCungCaps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNhaCungCap tblNhaCungCap = db.tblNhaCungCaps.Find(id);
            if (tblNhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(tblNhaCungCap);
        }

        // POST: Admin/tblNhaCungCaps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNCC,TenNCC,DiaChi,SDT")] tblNhaCungCap tblNhaCungCap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblNhaCungCap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblNhaCungCap);
        }

        // GET: Admin/tblNhaCungCaps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNhaCungCap tblNhaCungCap = db.tblNhaCungCaps.Find(id);
            if (tblNhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(tblNhaCungCap);
        }

        // POST: Admin/tblNhaCungCaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblNhaCungCap tblNhaCungCap = db.tblNhaCungCaps.Find(id);
            db.tblNhaCungCaps.Remove(tblNhaCungCap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DOAN/Areas/Admin/Views/tblNhaCungCaps/Create.cshtml
@model DOAN.Models.tblNhaCungCap

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .text-color {
        color: #3c3d46;
    }
</style>

<h2 class="text-color">Thêm mới nhà cung cấp</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2 text-color">Tên nhà cung cấp</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2 text-color">Địa chỉ</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2 text-color">Số điện thoại</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Danh sách", "Index")
</div>

DOAN/Areas/Admin/Views/tblNhaCungCaps/Delete.cshtml
@model DOAN.Models.tblNhaCungCap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h3>Bạn có chắc chắn xóa nhà cung cấp này không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên nhà cung cấp:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-primary" /> |
            @Html.ActionLink("Danh sách", "Index")
        </div>
    }
</div>

DOAN/Areas/Admin/Views/tblNhaCungCaps/Details.cshtml
@model DOAN.Models.tblNhaCungCap

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .text-color {
        color: #3c3d46;
    }
</style>

<h2 class="text-color">Thông tin chi tiết nhà cung cấp</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt class="text-color">
            Mã nhà cung cấp:
        </dt>

        <dd class="text-color">
            @Html.DisplayFor(model => model.MaNCC)
        </dd>

        <dt class="text-color">
            Tên nhà cung cấp:
        </dt>

        <dd class="text-color">
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt class="text-color">
            Địa chỉ:
        </dt>

        <dd class="text-color">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt class="text-color">
            Số điện thoại:
        </dt>

        <dd class="text-color">
            @Html.DisplayFor(model => model.SDT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaNCC }) |
    @Html.ActionLink("Danh sách", "Index")
</p>

DOAN/Areas/Admin/Views/tblNhaCungCaps/Edit.cshtml
@model DOAN.Models.tblNhaCungCap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .text-color {
        color: #3c3d46;
    }
</style>

<h2 class="text-color">Sửa thông tin nhà cung cấp</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaNCC)

    <div class="form-group">
        <div class="control-label col-md-2 text-color">Mã nhà cung cấp</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaNCC, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2 text-color">Tên nhà cung cấp</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2 text-color">Địa chỉ</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2 text-color">Số điện thoại</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Danh sách", "Index")
</div>

DOAN/Areas/Admin/Views/tblNhaCungCaps/Index.cshtml
@model IEnumerable<DOAN.Models.tblNhaCungCap>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DANH SÁCH NHÀ CUNG CẤP</h6>
        </div>
        @if (Session["role"] != null)
        {
            if (Session["role"].ToString() == Constant.ADMIN)
            {
                <a class="btn btn-primary ml-4 mt-2 pl-2" href="@Url.Action("Create")" style="width: 6rem;">Thêm mới</a>
            }
        }
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered dataTable text-dark" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Tên nhà cung cấp</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th width="18%">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenNCC)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DiaChi)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SDT)
                                </td>
                                <td>
                                    @if (Session["role"] != null)
                                    {
                                        if (Session["role"].ToString() == Constant.ADMIN)
                                        {
                                            <a href="@Url.Action("Edit","tblNhaCungCaps", new {id = item.MaNCC })" class="p-1 data-toggle= text-primary">Sửa</a><span>|</span>
                                            <a href="@Url.Action("Details","tblNhaCungCaps", new {id = item.MaNCC })" class="p-1 data-toggle= text-primary">Chi tiết</a>
                                        }
                                        else if (Session["role"].ToString() == Constant.EMPLOYEER)
                                        {
                                            <a href="@Url.Action("Details","tblNhaCungCaps", new {id = item.MaNCC })" class="p-1 data-toggle= text-primary">Chi tiết</a>
                                        }
                                    }
                                            
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@section scripts{
    <script src="~/Areas/Admin/assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.dataTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.11.5/i18n/vi.json'
                },
            });
        });
    </script>
}