DOAN/Models/tblQuyen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblQuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuyen()
        {
            this.tblNguoiDungs = new HashSet<tblNguoiDung>();
        }
    
        [Key]
        public int MaQuyen { get; set; }
        [Required(ErrorMessage ="Bạn chưa nhập tên quyền!")]
        public string TenQuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNguoiDung> tblNguoiDungs { get; set; }
    }
}

DOAN/Areas/Admin/Controllers/tblQuyensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DOAN.Models;

namespace DOAN.Areas.Admin.Controllers
{
    public class tblQuyensController : Controller
    {
        private QuanLyBanHangEntities1 db = new QuanLyBanHangEntities1();

        // GET: Admin/tblQuyens
        public ActionResult Index()
        {
            return View(db.tblQuyens.ToList());
        }

        // GET: Admin/tblQuyens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblQuyen tblQuyen = db.tblQuyens.Find(id);
            if (tblQuyen == null)
            {
                return HttpNotFound();
            }
            return View(tblQuyen);
        }

        // GET: Admin/tblQuyens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/tblQuyens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaQuyen,TenQuyen")] tblQuyen tblQuyen)
        {
            if (ModelState.IsValid)
            {
                db.tblQuyens.Add(tblQuyen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblQuyen);
        }

        // GET: Admin/tblQuyens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblQuyen tblQuyen = db.tblQuyens.Find(id);
            if (tblQuyen == null)
            {
                return HttpNotFound();
            }
            return View(tblQuyen);
        }

        // POST: Admin/tblQuyens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaQuyen,TenQuyen")] tblQuyen tblQuyen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblQuyen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblQuyen);
        }

        // GET: Admin/tblQuyens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblQuyen tblQuyen = db.tblQuyens.Find(id);
            if (tblQuyen == null)
            {
                return HttpNotFound();
            }
            return View(tblQuyen);
        }

        // POST: Admin/tblQuyens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblQuyen tblQuyen = db.tblQuyens.Find(id);
            db.tblQuyens.Remove(tblQuyen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DOAN/Areas/Admin/Views/tblQuyens/Create.cshtml
@model DOAN.Models.tblQuyen

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm quyền truy cập</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">Tên quyền</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenQuyen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenQuyen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Danh sách", "Index")
</div>

DOAN/Areas/Admin/Views/tblQuyens/Delete.cshtml
@model DOAN.Models.tblQuyen

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h3>Bạn có chắc chắn muốn xóa quyền truy cập này không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã quyền:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaQuyen)
        </dd>

        <dt>
            Tên quyền:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenQuyen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-primary" /> |
            @Html.ActionLink("Danh sách", "Index")
        </div>
    }
</div>

DOAN/Areas/Admin/Views/tblQuyens/Details.cshtml
@model DOAN.Models.tblQuyen

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thông tin chi tiết quyền truy cập</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã quyền:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaQuyen)
        </dd>

        <dt>
            Tên quyền:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenQuyen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaQuyen }) |
    @Html.ActionLink("Danh sách", "Index")
</p>

DOAN/Areas/Admin/Views/tblQuyens/Edit.cshtml
@model DOAN.Models.tblQuyen

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sửa thông tin quyền truy cập</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaQuyen)

    <div class="form-group">
        <div class="control-label col-md-2">Mã quyền</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaQuyen, new { htmlAttributes = new { @class = "form-control", @readonly="readonly" } })
            @Html.ValidationMessageFor(model => model.TenQuyen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Tên quyền</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenQuyen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenQuyen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Danh sách", "Index")
</div>

DOAN/Areas/Admin/Views/tblQuyens/Index.cshtml
@model IEnumerable<DOAN.Models.tblQuyen>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DANH SÁCH QUYỀN TRUY CẬP</h6>
        </div>
        <a class="btn btn-primary ml-4 mt-2 pl-2" href="@Url.Action("Create")" style="width: 6rem;">Thêm mới</a>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered dataTable text-dark" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Mã quyền</th>
                            <th>Tên quyền truy cập</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MaQuyen)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenQuyen)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit","tblQuyens", new {id = item.MaQuyen })" class="p-1 data-toggle= text-primary">Sửa</a><span>|</span>
                                    <a href="@Url.Action("Details","tblQuyens", new {id = item.MaQuyen })" class="p-1 data-toggle= text-primary">Chi tiết</a>@*<span>|</span>
                                    <a href="@Url.Action("Delete","tblQuyens", new {id = item.MaQuyen })" class="p-1 data-toggle= text-primary">Xóa</a>*@
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@section scripts{
    <script src="~/Areas/Admin/assets/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.dataTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.11.5/i18n/vi.json'
                },
            });
        });
    </script>
}